<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\CvAlInstante.Domain\CvAlInstante.Domain.csproj" />
    <ProjectReference Include="..\CvAlInstante.Infrastructure\CvAlInstante.Infrastructure.csproj" />
  </ItemGroup>
</Project>
